# Generated by Django 3.1.6 on 2021-03-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20210317_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='test_user', max_length=100),
            preserve_default=False,
        ),
    ]
